# Site settings
title: Damian's Blog
description: "A minimal blog template, build with Jekyll."
url: http://localhost:4000
author:
  name: "DamianZhou"
  email: "zhoucaidong@gmail.com"
  url: ""

# Build settings
safe: false
port: 4000
baseurl: /DamianBlog/ # Change this to your relative path (ex: /blog/), or leave just a /

source: .
destination: ./_site
plugins: ./_plugins
permalink: /:title

paginate: 8
paginate_path: /page:num/
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: 
    - no_intra_emphasis
    - tables
    - fenced_code_blocks
    - autolink
    - disable_indented_code_blocks
    - strikethrough
    - superscript
    - underline
    - highlight
    - footnotes
    - with_toc_data


# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
